# Défi Grosses Data 2018

## Data analysis

In [1]:
import numpy as np
import pandas as pd

In [2]:
input_file='./../data_meteo/train_1.csv'
df = pd.read_csv(input_file, header=0, delimiter=";")

In [3]:
df.head()

,date,insee,tH2_obs,capeinsSOL0,ciwcH20,clwcH20,ddH10_rose4,ffH10,flir1SOL0,fllat1SOL0,...,tH2,tH2_VGrad_2.100,tH2_XGrad,tH2_YGrad,tpwHPA850,ux1H10,vapcSOL0,vx1H10,ech,mois
0,2014-01-01,6088001,"5,5","0,198757136546071",0,0,4.0,"1,97026025179421","-386960,595711332","-94260,6825228745",...,"9,03433839457696","-0,0849992375469188","0,00772475802493392","-0,0130238175028849","3,85282547789542","1,33031959472908","10,6646529229256","-2,85313363311258",1,janvier
1,2014-01-01,31069001,"4,80000019073486","8,59003572334496",0,0,3.0,"2,75596235112772","-200181,123870512","2282,95168732758",...,"3,85312782895852","1,3961383839632","0,00503648990159295","0,000809948849897301","8,47669885903599","-2,04001975406606","15,4620428472963","3,01961425625813",1,janvier
2,2014-01-01,33281001,"8,89999961853027","69,2038560112975",0,"1,02676193002635e-06",3.0,"3,41128316482305","-62310,3402969763","9483,69131593718",...,"8,5851837142832","0,387328512262545","0,00137216533093163","9,73835595101643e-06","7,64306976009556","3,02961043434631","17,3436002872158","4,88984864364851",1,janvier
3,2014-01-01,35281001,"6,80000019073486","65,2703161986173",0,0,3.0,"4,65563298188788","-61612,1200751398","-48356,4758309944",...,"7,30413042337057","-0,0892667196392294","0,000400819544869389","-6,68360027845141e-05","7,08903008062009","-1,02744613589718","13,9818471868002","8,07997347730339",1,janvier
4,2014-01-01,59343001,"5,40000009536743","5,9325045395199",0,0,3.0,"5,85593047786356","-39553,1099550016","-1022,91424209591",...,"5,82971476606929","-0,489606173558059","0,000204035881467552","-0,00019073915318906","4,54607464998947","2,8025541469202","9,94160869717598","7,95548911579665",1,janvier